export const WIDGET_TYPES = [
  { value: "qbittorrent", label: "qBittorrent" },
  { value: "transmission", label: "Transmission" },
  { value: "deluge", label: "Deluge" },
  { value: "proxmox", label: "Proxmox" },
  { value: "sonarr", label: "Sonarr" },
  { value: "radarr", label: "Radarr" },
  { value: "lidarr", label: "Lidarr" },
  { value: "prowlarr", label: "Prowlarr" },
  { value: "bazarr", label: "Bazarr" },
  { value: "sabnzbd", label: "SABnzbd" },
  { value: "docker", label: "Docker Engine" },
  { value: "portainer", label: "Portainer" },
  { value: "npm", label: "Nginx Proxy Manager" },
  { value: "pihole", label: "Pi-hole" },
  { value: "adguard", label: "AdGuard Home" },
  { value: "technitium", label: "Technitium DNS" },
  { value: "jellyseerr", label: "Jellyseerr" },
  { value: "overseerr", label: "Overseerr" },
  { value: "jellyfin", label: "Jellyfin" },
  { value: "plex", label: "Plex" },
  { value: "tautulli", label: "Tautulli" },
  { value: "nextcloud", label: "Nextcloud" },
  { value: "homeassistant", label: "Home Assistant" },
  { value: "immich", label: "Immich" },
  { value: "mealie", label: "Mealie" },
  { value: "kavita", label: "Kavita" },
  { value: "audiobookshelf", label: "Audiobookshelf" },
  { value: "navidrome", label: "Navidrome" },
  { value: "paperless", label: "Paperless-ngx" },
  { value: "n8n", label: "n8n" },
  { value: "grafana", label: "Grafana" },
  { value: "qnap", label: "QNAP" },
  { value: "filebrowser", label: "FileBrowser" },
  { value: "guacamole", label: "Guacamole" },
  { value: "fritzbox", label: "FRITZ!Box" },
  { value: "generic", label: "Generic HTTP" },
] as const;

export const API_KEY_WIDGETS = new Set([
  "sonarr",
  "radarr",
  "lidarr",
  "prowlarr",
  "bazarr",
  "jellyseerr",
  "overseerr",
  "sabnzbd",
  "pihole",
  "adguard",
  "portainer",
  "jellyfin",
  "immich",
  "kavita",
  "plex",
  "technitium",
  "nextcloud",
  "audiobookshelf",
  "tautulli",
  "paperless",
  "n8n",
  "grafana",
]);

export const TOKEN_WIDGETS = new Set(["homeassistant", "mealie"]);

export const USERNAME_PASSWORD_WIDGETS = new Set([
  "qbittorrent",
  "transmission",
  "deluge",
  "filebrowser",
  "guacamole",
  "qnap",
  "npm",
  "navidrome",
]);
